spring.application.name=Account-Management
spring.datasource.url=jdbc:postgresql://localhost:5432/Account-Management
spring.datasource.username = postgres
spring.datasource.password=Temp@123456
spring.jpa.show-sql =true
spring.jpa.hibernate.ddl-auto=update


